/**
 * The TypeScript backtester must reproduce the Python research engine on
 * real data (BTC/ETH/SOL/HYPE daily closes, HYPE listing mid-sample).
 * Expected numbers are generated by research/trend_ensemble_backtest.py.
 */
import { readFileSync } from 'node:fs';
import { describe, expect, test } from 'vitest';
import { runBacktest, type TrendEnsembleParams } from '../src/index.js';

const fx = JSON.parse(
  readFileSync(new URL('./fixtures/parity-btc-eth-sol-hype.json', import.meta.url), 'utf8'),
) as {
  params: TrendEnsembleParams;
  feeRate: number;
  startMs: number;
  days: number[];
  closes: Record<string, Array<number | null>>;
  expected: {
    finalEquity: number; cagr: number; sharpe: number; maxDrawdown: number;
    avgGross: number; turnoverPerYear: number; equitySample: number[];
  };
};

describe('backtest parity with the Python research engine', () => {
  const res = runBacktest({ days: fx.days, closes: fx.closes }, fx.params, { feeRate: fx.feeRate, startMs: fx.startMs });

  test('final equity and headline stats match', () => {
    expect(res.points.at(-1)!.equity).toBeCloseTo(fx.expected.finalEquity, 10);
    expect(res.stats.cagr).toBeCloseTo(fx.expected.cagr, 10);
    expect(res.stats.sharpe).toBeCloseTo(fx.expected.sharpe, 8);
    expect(res.stats.maxDrawdown).toBeCloseTo(fx.expected.maxDrawdown, 10);
    expect(res.stats.avgGross).toBeCloseTo(fx.expected.avgGross, 10);
    expect(res.stats.turnoverPerYear).toBeCloseTo(fx.expected.turnoverPerYear, 8);
  });

  test('equity curve matches point by point', () => {
    const sample = res.points.filter((_, i) => i % 50 === 0).map((p) => p.equity);
    expect(sample).toHaveLength(fx.expected.equitySample.length);
    sample.forEach((v, i) => expect(v).toBeCloseTo(fx.expected.equitySample[i]!, 10));
  });
});
